name: Cypress Component Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Run Cypress Component Tests
        run: |
          cd client
          npx cypress run-ct --component

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots
