# .github/workflows/deploy-to-render.yml

name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Hook
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
